services:
  authentication_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      CONFIG_PATH: config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: strong_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: auth_service_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
